### ISSUE TITLE
Update Project Plan

### ISSUE THREAD

**Issue by ozankrkya** [bounswe/bounswe2024group11#278]
# 🧱 Description

Project plan defined and delivered for Milestone 1 should be updated in a way that includes more details about implementation. 

## 📋 Acceptance Criteria

- [ ] Tasks and sub-tasks should be defined under three different teams, backend, frontend (web) and mobile.
- [ ] Durations, start-end dates should be defined for tasks.
- [ ] ProjectLibre file should be updated with the latest changes.

**Comment by meminciftci** [comment]
The doc file can be accessed [here](https://docs.google.com/document/d/19cxjWb9LdgpQiqAh1cBXYYWsEI1pcCoAqI-TSESdW-I/edit?usp=drive_link)

**Comment by meminciftci** [comment]
Updated Gantt and Network chart can be seen [here](https://github.com/bounswe/bounswe2024group11/wiki/Project-Plan) on the bottom of the page. Documentation will be also changed.

**Comment by meminciftci** [comment]
Updated the backend part of the implementation phase. It can be seen [here](https://github.com/bounswe/bounswe2024group11/wiki/Project-Plan)

Can you check it if there is anything I missed? @ozankrkya

**Comment by meminciftci** [comment]
Updated the frontend part of the implementation phase. It can be seen [here](https://github.com/bounswe/bounswe2024group11/wiki/Project-Plan)

Can you check it if there is anything I missed? @hks1444

**Comment by ozankrkya** [comment]
Everything looks fine except one part. 
CI/CD pipeline is configured earlier than it is planned thus it has to be moved before the milestone2. 
It took 2 days to complete as expected, the task is completed yesterday.

**Comment by meminciftci** [comment]
All the project plan has been updated: [final form](https://github.com/bounswe/bounswe2024group11/wiki/Project-Plan).

Which parts have been updated?

1. The part about using GitHub projects is deleted since we do not use it much.
2.  Software design part become more detailed.
3. End of Design Phase Milestone has added replacing our previously named milestone 2.
4. Implementation part is changed. It consists of three main branch: Backend, frontend, and mobile.
5. Our milestones are now as follows: Milestone 1, End of Design Phase, Milestone 2 and Milestone 3.
6. Chart descriptions and charts themselves are changed.

Additionally, the specified backend part of the implementation phase is now changed. 

@ozankrkya @hks1444

**Comment by ozankrkya** [comment]
I updated the descriptions of the subtasks in the backend part of the project plan.

**Comment by meminciftci** [comment]
The final form of the project plan can be accessed [here](https://github.com/bounswe/bounswe2024group11/wiki/Project-Plan).

Backend, frontend and mobile subtasks have been detailed and updated.
