### ISSUE TITLE
Milestone 2 Backend Backlog

### ISSUE THREAD

**Issue by MucahitErdoganUnlu** [bounswe/bounswe2024group11#625]
# 🧱 Description
- [x] Take Quiz CRUD (mücahit)
- [ ]  Forum Answer CRUD (ozan)
- [x] Forum Upvote/Downvote CRUD (çiftçi)
- [x] Forum Bookmark CRUD (ceyda)

- [ ] Hint (2nd phase of implementations)
- [ ] Quiz Puanlama - update TakeQuiz and Quiz CRUD endpoints
## 📋 Acceptance Criteria

- [ ] Task is done

**Comment by MucahitErdoganUnlu** [comment]
# 🧱 Description
Essential:
- [ ] Quiz difficulty
- [ ] is_bookmarked, is_upvoted, is_downvoted
- [ ] semantic search for quiz and forum question

Bonus:
- [ ] hint
- [ ] badge
- [ ] düello
#### To be reviewed by: @username

## 📋 Acceptance Criteria

- [ ] Task is done

**Comment by MucahitErdoganUnlu** [comment]
is_bookmarked vs: [commit](https://github.com/bounswe/bounswe2024group11/commit/2ed45c29bf9655d17f7d6770090c0907a38d3594)

**Comment by MucahitErdoganUnlu** [comment]
- [ ] hint
- [ ] search
- [ ] puanlama
- [ ] difficulty
