### ISSUE TITLE
Create Demo Scenario For Final Milestone

### ISSUE THREAD

**Issue by MucahitErdoganUnlu** [bounswe/bounswe2024group11#734]
# 🧱 Description

We should determine the main features to demo and out solutions to the feedbacks from CM2.

- Determine the status of the project and the major features to display: @hks1444 @Meminseeker @yunuskaydin @umitcan07 
- Presentation UX and Accessibility Concerns: @umitcan07 
- User Persona: @ceydanursen @umitcan07 
- Scenario Flow: @meminciftci @MucahitErdoganUnlu @ozankrkya @ArdaVural 

## 📋 Acceptance Criteria

- [x] Presentation scenario includes all core functions and new developments of the app.
- [x] Scenario flow is logical, intuitive, and easy to follow.
- [x] Different user types should be handled in the scenario.
- [x] All features (e.g., quiz creation, semantic search) work seamlessly during the demonstration.

**Comment by Meminseeker** [comment]
Add a document on wiki for major tasks and pre-determination of milestone 3 presentation: [document](https://github.com/bounswe/bounswe2024group11/wiki/Milestone-3-Presentation)

**Comment by Meminseeker** [comment]
## Issues:

#730

**Comment by ozankrkya** [comment]
We have decided on the first version of the presentation scenario [here](https://github.com/bounswe/bounswe2024group11/wiki/Final-Customer-Milestone-%E2%80%90-Demo-Presentation-Scenario)
